[package]
name = "skadi-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
skadi-core.workspace = true
skadi-protocol.workspace = true
skadi-transport.workspace = true

tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
hex.workspace = true
base64.workspace = true
futures = { version = "0.3", optional = true }
rustls.workspace = true
rustls-pki-types.workspace = true
rustls-native-certs.workspace = true
tokio-rustls.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
tun = { version = "0.8", features = ["async"] }
netstack-smoltcp = "0.2.4"
futures = "0.3"
libc = "0.2"
