//! Протоколы: SOCKS5, VLESS, REALITY.

pub mod socks5;

pub use socks5::{
    AuthMethod, Socks5Config, Socks5Handler, UserCredential,
    REP_ADDRESS_NOT_SUPPORTED, REP_COMMAND_NOT_SUPPORTED,
    REP_CONNECTION_REFUSED, REP_GENERAL_FAILURE, REP_HOST_UNREACHABLE,
    REP_NETWORK_UNREACHABLE, REP_SUCCEEDED,
};
