[server]
listen = "0.0.0.0:443"

# TLS inbound (рекомендуется для VLESS в продакшене).
# [transport.tls]
# enabled = true
# cert = "certs/server.pem"
# key = "certs/server.key"
# alpn = ["h2", "http/1.1"]

[protocol.socks5]
enabled = false

[protocol.vless]
enabled = true

[[protocol.vless.users]]
id = "b831381d-6324-4d53-ad4f-8cda48b30811"
email = "alice@example.com"
